### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by uktricky** [Daveiano/weewx-wdc-interceptor-docker#6]
Using your dockerfile to build an Image and then your same docker run 

docker run \
-d \
-p 9877:9877 \
-v /home/xx/docker/weewx/db:/home/weewx-data/archive \
-v /home/xx/docker/weewx/public_html:/home/weewx-data/public_html \
--name weewx \
--restart unless-stopped \
weewx:latest

But docker fails to start due to the six issue? Docker logs are below: - Can you help / give advice?

Starting enhanced syslogd: rsyslogd.
Starting weewx
Traceback (most recent call last):
  File "/home/weewx-data/weewx-venv/bin/weewxd", line 8, in <module>
    sys.exit(main())
  File "/home/weewx-data/weewx-venv/lib/python3.10/site-packages/weewxd.py", line 160, in main
    engine = weewx.engine.StdEngine(config_dict)
  File "/home/weewx-data/weewx-venv/lib/python3.10/site-packages/weewx/engine.py", line 89, in __init__
    self.loadServices(config_dict)
  File "/home/weewx-data/weewx-venv/lib/python3.10/site-packages/weewx/engine.py", line 157, in loadServices
    obj = weeutil.weeutil.get_object(svc)(self, config_dict)
  File "/home/weewx-data/weewx-venv/lib/python3.10/site-packages/weeutil/weeutil.py", line 1404, in get_object
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/weewx-data/bin/user/forecast.py", line 529, in <module>
    import six.moves.http_client
ModuleNotFoundError: No module named 'six'
WEEWX_HOME: /home/weewx-data
Starting rsyslog

**Comment by Daveiano** [comment]
Yes, I also noticed this in my local environment. Updated the pip install command to include `six` fixed it. I don't know how this came, yet. It could be an update in any of the dependencies.
